In [ ]:
import pandas as pd
import csv

In [17]:
file_path = 'data/set_images.txt'
data = []

# Open the file and parse the tab-separated values
with open(file_path, 'r') as file:
    reader = csv.reader(file, delimiter='\t')
    for row in reader:
        # Process each row (fields are accessible as elements of the row list)
        try:
            image_id, image_url, annotation, event = row
            data.append([image_id, image_url, annotation, event])
        except:
            pass
        # Perform operations with the parsed data
#         print(f"Image ID: {image_id}, Image URL: {image_url}, Annotation: {annotation}, Event: {event}")

In [18]:
df = pd.DataFrame(data, columns=['Image ID', 'Image URL', 'Annotation', 'Event'])

In [24]:
df

,Image ID,Image URL,Annotation,Event
0,image_id,image_url,annotation,event
1,boston_fake_01,http://i.imgur.com/LvoCC5T.jpg,fake,boston
2,boston_fake_02,http://instagram.com/p/YN7_ThPXrU/,fake,boston
3,boston_fake_03,https://o.twimg.com/2/proxy.jpg?t=HBgeaHR0cDov...,fake,boston
4,boston_fake_04,http://media.tumblr.com/a813460e72a178d8127b50...,fake,boston
...,...,...,...,...
371,bringback_fake_03,https://pbs.twimg.com/media/BoBFly8IQAEK881.jpg,fake,bringback
372,bringback_fake_04,https://pbs.twimg.com/media/BoBFzniIEAABAaP.jpg,fake,bringback
373,bringback_fake_05,https://pbs.twimg.com/media/BnLFu3DIUAECtam.jpg,fake,bringback
374,bringback_fake_06,https://pbs.twimg.com/media/BmjchgkIQAAUbds.jpg,fake,bringback
375,bringback_fake_07,https://pbs.twimg.com/media/Bo8v1C7IEAAxmGa.jpg,fake,bringback

In [27]:
df_labels = df[['Image URL', 'Annotation']][1:]

In [28]:
df_labels

                                             Image URL Annotation
1                       http://i.imgur.com/LvoCC5T.jpg       fake
2                   http://instagram.com/p/YN7_ThPXrU/       fake
3    https://o.twimg.com/2/proxy.jpg?t=HBgeaHR0cDov...       fake
4    http://media.tumblr.com/a813460e72a178d8127b50...       fake
5                      http://i.imgur.com/uxAh4wwh.jpg       fake
..                                                 ...        ...
371    https://pbs.twimg.com/media/BoBFly8IQAEK881.jpg       fake
372    https://pbs.twimg.com/media/BoBFzniIEAABAaP.jpg       fake
373    https://pbs.twimg.com/media/BnLFu3DIUAECtam.jpg       fake
374    https://pbs.twimg.com/media/BmjchgkIQAAUbds.jpg       fake
375    https://pbs.twimg.com/media/Bo8v1C7IEAAxmGa.jpg       fake

[375 rows x 2 columns]

In [33]:
df_fake = df[df['Annotation'] == 'fake']
df_real = df[df['Annotation'] == 'real']

In [34]:
print("Fakes: ", df_fake.shape)
print("Reals: ", df_real.shape)

Fakes:  (165, 4)
Reals:  (210, 4)